apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ragflow.fullname" . }}
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
        {{- if .Values.mcp.enabled }}
        - {{ .Values.mcp.ingress.host | quote }}
        {{- end }}
  rules:
    {{- if .Values.mcp.enabled }}
    - host: {{ .Values.mcp.ingress.host | required "mcp.ingress.host is required whan mcp.enabled is set" | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "ragflow.fullname" . }}-mcp
                port:
                  name: mcp
    {{- end }}

    - host: {{ .Values.ingress.host | required "ragflow.ingress.host is required" | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "ragflow.fullname" . }}
                port:
                  name: http
