{{- if .Values.mcp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ragflow.fullname" . }}-mcp
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ragflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp
  template:
    metadata:
      labels:
        {{- include "ragflow.labels" . | nindent 8 }}
        app.kubernetes.io/component: mcp
    spec:
      # Kubernetes injects service link environment variables which accidentally match the name of variables
      # expected inside the mcp server script. So we disable this legacy Kubernetes behaviour here.
      enableServiceLinks: false
      {{- if or .Values.imagePullSecrets .Values.ragflow.image.pullSecrets }}
      imagePullSecrets:
        {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.ragflow.image.pullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
      - name: mcp
        image: {{ .Values.ragflow.image.repository }}:{{ .Values.ragflow.image.tag }}
        {{- with .Values.ragflow.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        command:
          - "./entrypoint.sh"
          - "--disable-webserver"
          - "--disable-taskexecutor"
          - "--enable-mcpserver"
          - "--mcp-host=0.0.0.0"
          - "--mcp-port=9382"
          - {{ printf "--mcp-base-url=http://%s-api" (include "ragflow.fullname" .) | quote }}
          - "--mcp-script-path=/ragflow/mcp/server/server.py"
          - "--mcp-mode=self-host"
          - {{ (printf "--mcp-host-api-key=%s" (.Values.mcp.ragflowApiKey | required "An API key is required when activating the MCP server")) | quote }}
          - "--no-transport-sse-enabled"
        ports:
          - containerPort: 9382
            name: http-mcp
        {{- with .Values.mcp.deployment.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ragflow.fullname" . }}-mcp
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
spec:
  selector:
    {{- include "ragflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-mcp
      name: mcp
  type: ClusterIP
{{- end }}