apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ragflow.fullname" . }}-ragflow-secrets
type: Opaque
stringData:
  RAGFLOW_SECRET_KEY: {{ .Values.ragflow.secret_key | required "ragflow.secret_key is required" | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | required "redis.password is required" | quote }}
  MINIO_PASSWORD: {{ .Values.minio.password | required "minio.password is required" | quote }}
  ELASTIC_PASSWORD: {{ .Values.elasticsearch.password | required "elasticsearch.password is required" | quote }}
