---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ragflow.fullname" . }}-ragflow-config
data:
  {{- range $key, $val := .Values.env }}
  {{- if $val }}
  {{ $key }}: {{ quote $val }}
  {{- end }}
  {{- end }}
  {{- /*
  Use host names derived from internal cluster DNS
  */}}
  REDIS_HOST: {{ printf "%s-redis.%s.svc" (include "ragflow.fullname" .) .Release.Namespace | quote }}
  DATABASE_TYPE: postgres
  DB_TYPE: postgres
  POSTGRES_HOST: {{ printf "%s-postgres.%s.svc" (include "ragflow.fullname" .) .Release.Namespace | quote }}
  POSTGRES_DBNAME: {{ .Values.postgres.dbname | quote }}
  MINIO_HOST: {{ printf "%s-minio.%s.svc" (include "ragflow.fullname" .) .Release.Namespace | quote }}
  ES_HOST: {{ printf "%s-es.%s.svc" (include "ragflow.fullname" .) .Release.Namespace | quote }}
  DOC_BULK_SIZE: {{ .Values.ragflow.docBulkSize | quote }}
  EMBEDDING_BATCH_SIZE: {{ .Values.ragflow.embeddingBatchSize | quote }}
  REGISTER_ENABLED: {{ .Values.ragflow.registerEnabled | quote }}
  {{- with .Values.ragflow.hfEndpoint }}
  HF_ENDPOINT: {{ . | quote }}
  {{- end }}
  {{- with .Values.ragflow.maxContentLength }}
  MAX_CONTENT_LENGTH: {{ . | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ragflow.fullname" . }}-service-config
data:
  {{- with .Values.ragflow.service_conf }}
  local.service_conf.yaml: |
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Values.ragflow.llm_factories }}
  llm_factories.json: |
    {{- . | toPrettyJson | nindent 4 }}
  {{- end }}
