---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ragflow.fullname" . }}
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ragflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ragflow
  {{- with .Values.ragflow.deployment.strategy }}
  strategy:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "ragflow.labels" . | nindent 8 }}
        app.kubernetes.io/component: ragflow
      annotations:
        checksum/ragflow-secrets: {{ include (print $.Template.BasePath "/ragflow-secrets.yaml") . | sha256sum }}
        checksum/ragflow-config: {{ include (print $.Template.BasePath "/ragflow-config.yaml") . | sha256sum }}
        checksum/ragflow-nginx-config: {{ include (print $.Template.BasePath "/ragflow-nginx-config.yaml") . | sha256sum }}
    spec:
      # Kubernetes injects service link environment variables which accidentally match the name of variables
      # expected inside the mcp server script. So we disable this legacy Kubernetes behaviour here.
      enableServiceLinks: false
      {{- if or .Values.imagePullSecrets .Values.ragflow.image.pullSecrets }}
      imagePullSecrets:
        {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.ragflow.image.pullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
      - name: ragflow
        image: {{ .Values.ragflow.image.repository }}:{{ .Values.ragflow.image.tag }}
        {{- with .Values.ragflow.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        command:
          - "./entrypoint.sh"
          - "--disable-taskexecutor"
        ports:
          - containerPort: 80
            name: http
          - containerPort: 9380
            name: http-api
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/ragflow.conf
            subPath: ragflow.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/proxy.conf
            subPath: proxy.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            name: nginx-config-volume
          {{- with .Values.ragflow.service_conf }}
          - mountPath: /ragflow/conf/local.service_conf.yaml
            subPath: local.service_conf.yaml
            name: service-conf-volume
          {{- end }}
          {{- with .Values.ragflow.llm_factories }}
          - mountPath: /ragflow/conf/llm_factories.json
            subPath: llm_factories.json
            name: service-conf-volume
          {{- end }}
        envFrom:
          - secretRef:
              name: {{ include "ragflow.fullname" . }}-ragflow-secrets
          - configMapRef:
              name: {{ include "ragflow.fullname" . }}-ragflow-config
        {{- with .Values.ragflow.deployment.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      volumes:
        - name: nginx-config-volume
          configMap:
            name: {{ include "ragflow.fullname" . }}-nginx-config
        - name: service-conf-volume
          configMap:
            name: {{ include "ragflow.fullname" . }}-service-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ragflow.fullname" . }}
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
spec:
  selector:
    {{- include "ragflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
  type: {{ .Values.ragflow.service.type }}
---
{{- if .Values.ragflow.api.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ragflow.fullname" . }}-api
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
spec:
  selector:
    {{- include "ragflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-api
      name: http-api
  type: {{ .Values.ragflow.api.service.type }}
{{- end }}
